#!/bin/bash

REPO="Pancongwen/resume-library"
release=$1                       # tag name or the word "latest"
FILE="$2.zip"      # the name of your release asset file, e.g. build.tar.gz
GITHUB="https://api.github.com"

Parameter_judge() {
    correct_num="$1"
    real_num="$2"
    if [ "$correct_num" != "$real_num" ];then
        Usage
    fi
}

Usage() {
    echo "Usage: $0 [TAG]/\"latest\" [FILE_NAME]"
    exit 1
}

Parameter_judge 2 $#

if [ "$release" = "latest" ]; then
    # Github should return the latest release first.
    parser=".[].assets | map(select(.name == \"$FILE\"))[].id"
else
    echo $release
    parser=". | map(select(.tag_name == \"$release\"))[0].assets | map(select(.name == \"$FILE\"))[0].id"
fi;

asset_id=`curl -s $GITHUB/repos/$REPO/releases | jq "$parser"`


if [ "$asset_id" = "null" ]; then
    >&2 echo "ERROR: release not found $release"
    exit 1
fi;

 
file_url=`curl  -s -i $GITHUB/repos/$REPO/releases/assets/$asset_id | \
                grep "browser_download_url" | \
                awk -F '"' '{print $4}'`

echo $file_url
# download package
curl "$file_url" -i -o $FILE

